language: java
sudo: required
install: true

addons:
  sonarcloud:
    organization: "compartia-github"
    token:
      secure: "LOojO1g+VqNHRYyxShrDHdzjxZ5gImuGjy/0Yis2x3hx7xm+F/d07ah8w88NXOsVdDioKPaxuC6Tlf+GLEaUFO9anC0MzxFln2SlWZA1nza9AoUTB9bOfQm9FBTrOsjSwRyW64GnZiou1cP5h8Dn5J5mrlNX/RShz5GxMrBrVsTLcRRwuy1A3REZ4Mv1CJ6BuTIi4HvM/VOYzIKoiAyPdaGswHioV0jGQjmlSNGePu9sSC7exDL4nO72YfSeN7skOE0Q42k8/wcFIC2S9cS9SqBDRNx37kaJxPVGyUvvHW8gLSDDlyyZQxjIj3q9wAKKxf7KuzOeOK/Ojnkxkvh/wm2ycr/+Xm99a5vRIstMWgHjZJIcXDpI6JPE/krck90zAq/UKYHnylyDr8djKG17XojNNpHMPyS7cZC2hDAg9bwPjB2iDRWFzq4c/7rTJ2kSLcx4cxd9zRX5MY09y+AWt+OkWdgqYKw3wnDosLAbmSPth3Obp4s8Q1ZvU4H0rRiQjAMH1ahRQbS2WGB7mGG2lgUf5yMYsjDyApjS/TlHHSL8DGrdk40vt0fPqJsXSK1JGgC5eSCIs1a2J/ZTr2zJquqa1+RQzJRybAIqqKQDyp4vIQcDGyQFq0LX005CRJLOp/i84xaJxQ4z8kvcHNAuhKH0z7SgxmapOUqEckXTa0g="


script: 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
after_success: 
  - ls ./target|grep jar
  - mv ./target/$(ls ./target|grep .with-dependencies.jar) ./target/kt-advance-xml-$TRAVIS_TAG.jar
  
deploy:
  provider: releases
  api_key:
    secure: "ME2OQI7tKB9ceogQAgY1HOihRvxF8zmj9czNZj8t7umSJhCVomb2ys2uXztn5HV42asAVVpMosEKeHNMR8/DAjS1p0WFH7j61vEbisREfLIxrjiOXbfp9dOe5RA+3m5KYcn6kwxe9bv0CKy+WOw1iRpUV7OfvY7N3BkEvly3ne/k9Lu1tIb/QnhTtG9wmyiE9MLPfEETe94y49JBfsNW2pLzCMnwnlJ0AnmsxFIcCuV5g0UWNaJg13bcRHFBpGeoBD2mcBgf5dFd5RR7C56ABVGIuurEuqDV+tVsKtRZR33RaiMkcU8ctgBKq32cExs/GG7gVvHoI9lPXBcDaCg6uPzTgc/uZKfkedei7zK0dRoVm7quwMPgigU3IcoqQ7IIBtuCUv9rB7Vi/W7WpNUi4a+5G1/WqKh+B+AHAQ467pP6/TQSSh4h12cGp5v8pMmBkRk5UPP86T4PeSp4BhRfIEW3E8NFMegSDj7Y2xJ5tQQkYh7XCjp8Wd/LRWMTe4sTlvoYuSgUJ6LRnfRAci9Bx3koV7nAMJHTuvDKwyizVcMLs2YmqTAM3eosx//1wRqD3t8yy58r3FsF47KSJrPcQr2ON12UOhgOQRC0wZubNn3dvF4gn28YIBSVWPL8TFPczE512h6WrwDbaIBF1zt/xPeSx0fTP6WMQjttcm54Mjg="
  file: target/kt-advance-xml-$TRAVIS_TAG.jar
  skip_cleanup: true
  on:
    tags: true
